# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(595, 149)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 50, 442, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.single_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.single_btn.setMinimumSize(QtCore.QSize(120, 40))
        self.single_btn.setObjectName("single_btn")
        self.horizontalLayout.addWidget(self.single_btn)
        self.quit = QtWidgets.QPushButton(self.layoutWidget)
        self.quit.setMinimumSize(QtCore.QSize(120, 40))
        self.quit.setObjectName("quit")
        self.horizontalLayout.addWidget(self.quit)

        self.retranslateUi(Dialog)
        self.quit.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Coal Assistant"))
        self.single_btn.setText(_translate("Dialog", "开始竞拍"))
        self.quit.setText(_translate("Dialog", "退出"))
